# Generated by Django 4.0.2 on 2022-02-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_customer_booking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastname',
        ),
    ]
