# Generated by Django 4.0.2 on 2022-02-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_firstname_remove_booking_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
