# Generated by Django 4.0.2 on 2022-02-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_firstname_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
    ]
