# Generated by Django 4.0.2 on 2022-02-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hostel_hostel_name'),
        ('room', '0003_alter_room_room_no'),
        ('booking', '0009_remove_booking_email_remove_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hostel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel', to_field='hostel_name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='room.room', to_field='room_no'),
        ),
    ]
