# Generated by Django 4.0.2 on 2022-02-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_booking_user_booking_email_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hostel',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
