# Generated by Django 3.0.8 on 2022-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.CharField(default='not yet described', max_length=250),
        ),
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
