# Generated by Django 3.0.8 on 2022-03-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20220226_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='room_number',
            new_name='Number_of_rooms',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
