# Generated by Django 3.0.8 on 2022-03-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20220301_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
