# Generated by Django 3.0.8 on 2022-03-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hostel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
