# Generated by Django 4.0.2 on 2022-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
