# Generated by Django 4.0.2 on 2022-02-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=50)),
                ('total_rooms', models.CharField(max_length=50)),
                ('available_rooms', models.CharField(max_length=50)),
                ('room_prices', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
