# Generated by Django 4.0.2 on 2022-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
